[versions]
compose = "1.3.2"

[libraries]
composeActivity = { module = "androidx.activity:activity-compose", version = "1.6.1" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version = "1.1.0-alpha03" }
composePreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0" }
junit = { module = "junit:junit", version = "4.13.2" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.5.1" }

[bundles]
compose = ["composeActivity", "composeMaterial3", "composePreview", "composeUi"]
composeDebug = ["composeUiTestManifest", "composeUiTooling"]

[plugins]
androidApp = { id = "com.android.application", version = "7.3.1" }
androidLib = { id = "com.android.library", version = "7.3.1" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version = "1.7.20" }
